# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, unique=True)),
                ('translation', models.CharField(max_length=300)),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'either')])),
                ('category', models.IntegerField(choices=[(0, 'profile'), (1, 'message'), (2, 'any')])),
            ],
        ),
    ]
